# Generated by Django 2.2 on 2022-04-28 06:37

from django.db import migrations, models
import django.utils.timezone
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20220424_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='geom',
            field=djgeojson.fields.PolygonField(),
        ),
    ]
